[project]
name = "drf-skeleton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hiba Ibrahim Khanfar", email = "hibaibraheem140@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.87",
    "boto3-stubs~=1.43.87",
    "django>=6.1",
    "django-environ>=0.14.0",
    "django-storages>=1.14.6",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "python-magic>=0.4.27; sys_platform != 'win32'",
    "python-magic-bin>=0.4.14; sys_platform == 'win32'",
]

[project.scripts]
drf-skeleton = "drf_skeleton:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
